name: test
on:
  push:
    branches:
    - "**"
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macOS-latest
    steps:
    - name: setup go
      uses: actions/setup-go@v5
      with:
        go-version: 1.x
    - name: checkout
      uses: actions/checkout@v4
    - name: test
      run: go test -race -coverprofile coverage.out -covermode atomic
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
